### ISSUE TITLE
More space needed to read senses' definitions

### ISSUE THREAD

**Issue by tarnisil** [klab-ilc-cnr/maia-fe#105]
As title: we should reduce the white space at the right of the definition snippet and show more of the definition, both in the lexicon explorer and in the lexicon window

![image](https://github.com/MPapini91/maia-fe/assets/55898315/b702fd7b-cea7-430b-bc65-3fa8e4e6066d)

**Comment by tarnisil** [comment]
@MPapini91 is this closed issue already been deployed? On current deployed Maia-complit-new version the problem still exists

**Comment by MPapini91** [comment]
@tarnisil I ran a check on the deployment and it appears to me that descriptions (and labels in general, which led to issue https://github.com/klab-ilc-cnr/Maia/issues/32) are dynamically "trimmed" based on available space. Do you mean that the empty space on the side is still excessive?
