### ISSUE TITLE
partial sense definition description in inverse relation management

### ISSUE THREAD

**Issue by tarnisil** [klab-ilc-cnr/maia-fe#107]
When creating a "hyponym" relation between sense A and sense B, the system correctly create an "hypernym" relation between sense B and sense A, but does not show the full sense definition, including the "lemma" before the definition.

![image](https://github.com/MPapini91/maia-fe/assets/55898315/562dcc90-90f8-4164-afeb-456dea7ab81b)

**Comment by MPapini91** [comment]
@cienco  could you check if this issue is also resolved by the label change? Thank you

**Comment by cienco** [comment]
> @cienco could you check if this issue is also resolved by the label change? Thank you

yes it's solved
