### ISSUE TITLE
delete of lexical entries containing forms/lemmas leads to not user-oriented message

### ISSUE THREAD

**Issue by tarnisil** [klab-ilc-cnr/maia-fe#119]
As title.
If I try to delete a lexical entry containing forms and/or senses this error pops-up:

{"timestamp":"2024-01-12T15:03:28.687+00:00","status":500,"error":"Internal Server Error","message":"400 : \"The lexical entry cannot be deleted. Remove its forms and/or senses first.\"","path":"/maia/lexo/lexicon/delete/lexicalEntry"}

It would be better to have a more user-oriented warning massage saying that forms and senses have to be deleted before the lexical entry.

**Comment by MPapini91** [comment]
available in tags after 0.4.2
