### ISSUE TITLE
new lexical entry name does not appear in lexicon explorer

### ISSUE THREAD

**Issue by tarnisil** [klab-ilc-cnr/maia-fe#122]
After the renaming of a lexical entry, the new name does not appear in the lexicon explorer, which does not refresh its state automatically

<img width="1409" alt="image" src="https://github.com/klab-ilc-cnr/maia-fe/assets/55898315/f728e447-132e-40be-b2de-9b0eaa25c940">

**Comment by MPapini91** [comment]
> After the renaming of a lexical entry, the new name does not appear in the lexicon explorer, which does not refresh its state automatically
> 
> <img alt="image" width="1409" src="https://private-user-images.githubusercontent.com/55898315/296688865-f728e447-132e-40be-b2de-9b0eaa25c940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTc1NzcsIm5iZiI6MTcwNTMxNzI3NywicGF0aCI6Ii81NTg5ODMxNS8yOTY2ODg4NjUtZjcyOGU0NDctMTMyZS00MGJlLWIyZGUtOWIwZWFhMjVjOTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDExMTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OTljZDVmYTdiM2NlNDI2MmFkOGJkYTdlZDVjNTEwZjMyZTMxMjQ0MGNmYjlmYmM2MzAyZDgzNzhiOTUwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.APk_caM6e62Eg2BCYpIrgtIGE3Eyc88klx5uLAnFJaA">

As in the case of issue #103 , "Lexicon explorer" is filtered according to the initial name of the new entry. The window, therefore, automatically updates in content but there are no more entries for that string. Is the request to automatically update the filter string as well? The risk is a generalization of a specific case (if, for example, the user did not keep the initial filter but did a different search).

**Comment by tarnisil** [comment]
I would personally prefer not to have the explorer filtered by the new entry: once created the new entry I would like to see it in the lexicon explorer tree with all the others, ideally not closing the tree as it happens after each update

**Comment by MPapini91** [comment]
- [ ] remove filter on creation of a lexical entry
- [ ] checks that creating a new lexical entry does not close any expanded nodes in the tree

**Comment by MPapini91** [comment]
Built-in change, will enter next deployment
