### ISSUE TITLE
Ability to set the serverUrl at "deploy" time

### ISSUE THREAD

**Issue by magoafono** [klab-ilc-cnr/maia-fe#165]
Attualmente la serverUrl è essegnata staticamente tramite l'environment di Angular.
Sarebbe utile avere la possibilità di impostare la serverUrl a "deploy time" tramite file esterno (json o altro) in modo da non dover cambiare la URL nell'environment prima della compilazione  oppure direttamente nel compilato  (main.js)
Infatti non è detto che si sappia la URL della macchina di deploy in quel momento.

Currently the serverUrl is statically assigned via the Angular environment.
It would be useful to have the possibility of setting the serverUrl to "deploy time" via an external file (json or other) so as not to have to change the URL in the environment before compilation or directly in the compiled (main.js)
In fact, it is not certain that we know the URL of the deployment machine at that moment.

**Comment by MPapini91** [comment]
Dovrebbe ricollegarsi ai link che mi avevi inviato:

https://stackoverflow.com/questions/61877574/configuring-angular-production-files-after-build

https://chat.openai.com/share/82e88b80-f2a4-4153-aff7-36b7accc6556

**Comment by magoafono** [comment]
Andrebbe capito se una soluzione che usi window.location.hostname possa fare al caso nostro. Forse sarebbe più semplice ma vanno capite le implicazioni e side effect.
https://stackoverflow.com/questions/72507988/how-to-get-server-ip-address-in-an-angular-application

**Comment by magoafono** [comment]
E' un po' una aggeggiata ma se nell'environmet la serverUrl è costruita in questo modo la GUI riesce a calcolarla a runtime.

`const serverUrl = window.location.protocol+"//"+window.location.hostname+window.location.pathname.substring(0, window.location.pathname.lastIndexOf("/"))+'/maia';`

rimane il problema della directory `assets` che non riesco a proxarla correttamente.
