### ISSUE TITLE
Indirect relationship details

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/maia-fe#54]
When the fields "comment," "description," "example," and "confidence" (depleted properties) have been entered, the add button must be disabled to re-enable itself in case one of the properties becomes available again upon entry.

**Comment by cienco** [comment]
@MPapini91 can you add a screenshot showing where the problem happens

**Comment by MPapini91** [comment]
<img width="759" alt="image" src="https://github.com/klab-ilc-cnr/maia-fe/assets/61142119/59fb27e4-e5fb-4485-af87-3ed159ecb4d2">
<img width="668" alt="image" src="https://github.com/klab-ilc-cnr/maia-fe/assets/61142119/7863046d-949d-4efa-b426-f45071377d57">
<img width="787" alt="image" src="https://github.com/klab-ilc-cnr/maia-fe/assets/61142119/f4a0b0d6-033f-4017-8891-adba1bac320c">
