### ISSUE TITLE
"@" character appears following label of form after creation and renaming

### ISSUE THREAD

**Issue by tarnisil** [klab-ilc-cnr/maia-fe#91]
As title.

![image](https://github.com/MPapini91/maia-fe/assets/55898315/c94d1b48-5781-488c-b56d-2c4efc5dfa59)

**Comment by MPapini91** [comment]
Fixed by deploying [tag 0.4.2](https://github.com/klab-ilc-cnr/maia-fe/releases/tag/0.4.2)
