### ISSUE TITLE
White space in the rightmost part of the semantic relations sense's tab 

### ISSUE THREAD

**Issue by tarnisil** [klab-ilc-cnr/maia-fe#95]
As title: could it be removed?

![image](https://github.com/MPapini91/maia-fe/assets/55898315/05d64ca8-745f-422d-bd7b-9f4ae5bca37b)

**Comment by cienco** [comment]
Seems to be fixed already in the last develop version @MPapini91

**Comment by MPapini91** [comment]
> Seems to be fixed already in the last develop version @MPapini91


Above a certain panel width the problem still occurs. In the example images I am getting a calculated width of 1940.04px and a height of 797.292px

<img width="1511" alt="image" src="https://github.com/klab-ilc-cnr/maia-fe/assets/61142119/5dd89cb6-dcd9-429b-ba1a-a742b7f0994a">

<img width="1525" alt="image" src="https://github.com/klab-ilc-cnr/maia-fe/assets/61142119/d0102e4d-5a01-4762-9a68-4c491e69ba5d">
